#!/usr/bin/env bash
# Printing Holberton School 10x with #9 also printing 'hi on new line

m=0
while [ $m -lt 10 ]
do
    if [ $m = 8 ]; then
	echo "Holberton School"
	echo "Hi"

    else
	echo "Holberton School"
    fi
    ((m++))

done
