#!/usr/bin/env bash
# Using loops and case statement to print 1-20
# with specific outputs for 4; 9: 17

m=1
while ((m<21))
do
	case $m in
	     4)
		echo $m
		echo "bad luck from China"
		;;

	      9)
		 echo $m
		 echo "bad luck from Japan"
		 ;;
	       17)
		  echo $m
		  echo "bad luck from Italy"
		  ;;
	        *)
		  echo $m
		  ;;

	  	esac
	   ((m++))

done
