#!/usr/bin/env bash
#Display number 1-20;
#On 4th time displays bad luck from China
#On 9th time displays bad luck from Japan
#On 17th time displays bad luck from Italy

m=0
while [ $m -lt 20 ]
      do
      ((m++))

case $m in
4)
     echo "4"
     echo "bad luck from China"
     ;;

9)
     echo "9"
     echo "bad luck from Japan"
     ;;

17)
     echo "17"
     echo "bad luck from Italy"
     ;;

*)
     echo "$m"
     ;;

esac
done
