#!/usr/bin/env bash
# Script that displays: content of current dir
# :In a list format
# :Where only part of the name is displayed after first '-'

for name in *
do
	echo "$name" | cut -d '-' -f 2
done
